### ISSUE TITLE
Release Tasks for v2.1.0

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1579]
Optuna [v2.1.0](https://github.com/optuna/optuna/milestone/27) -- in September, 2020

Compatibility
- Optuna v2.1.0 will be the last version that supports Python 3.5. See #1067.
- Configuration files for `AllenNLPExecutor` may need to be updated. See #1544.
- Make Optuna PEP 561 Compliant. See #1719

Features (TBD):
- [x] IPOP-CMA-ES #1548
- [x] Improvement of `FrozenTrial` #1503

Examples
- [x] MLFlow on Kubernetes #1464

**Comment by hvy** [comment]
To be included as a highligh/compat change https://github.com/optuna/optuna/issues/1719.

**Comment by hvy** [comment]
Marking IPOP-CMA-ES as checked 🎉

**Comment by hvy** [comment]
See also https://github.com/optuna/optuna/pull/1791

**Comment by hvy** [comment]
See also https://github.com/optuna/optuna/issues/1795, although this might be beyond the scope of this issue.

**Comment by hvy** [comment]
#1791 is now merged. Let me close this issue as fixed!
