### ISSUE TITLE
A proposal of `MutualInformationImportanceEvaluator`

### ISSUE THREAD

**Issue by kstoneriv3** [optuna/optuna#1794]
## Motivation

I propose a new parameter importance evaluation method using mutual information between the objective function and each parameter. ~Though there are some problems with this functionality,~(<- mostly solved!) I would like to discuss how we might be able to support this feature.

## Description

Mutual information can be estimated by using multivariate Parzen estimators, which is originally implemented for multivariate TPE sampler. In the closed issue (#1786) and [my repository](https://github.com/kstoneriv3/optuna/tree/mutual-information-feature-importance/optuna/importance/_mutual_information), a draft of the MutualInformationImportanceEvaluator is presented (Note: my repo is a newer version of the draft!).
 
#### Numerical Integration
Numerical integration was used for the calculation of mutual information. By substituting all density appearing in the definition of mutual information, we can easily apply numerical integration to calculate mutual information. 

Note that I used a normalized variant of mutual information that is called the information quality ratio (IQR). For detail see [Wikipedia (Mutual Information)](https://en.wikipedia.org/wiki/Mutual_information#Normalized_variants) or [this article](https://www.mdpi.com/1099-4300/19/11/631).

One advantage of using integration is that the estimate is guaranteed to be positive as the calculated quantity is essentially the KL divergence between Parzen estimators of joint density and product of marginal densities. (At first, I calculated mutual information by sample average but it suffered from unstable estimate values like a negative estimate.)

### Comparison with FANOVA
In my benchmark experiment, `MutualInformationImportanceEvaluator` was less sensitive to the relevance of the hyperparameters than `FanovaImportanceEvaluator`. In the toy experiments where there are some totally irrelevant hyperparameters, `MutualInformationImportanceEvaluator` gave relatively higher importance to irrelevant hyperparameters when the sample size is large enough. 

However, when we look at the ranking of the hyperparameters, we get more or less the same results from both importance evaluator, which implies that `MutualInformationImportanceEvaluator` is almost as good as `FanovaImportanceEvaluator` if the importance were properly scaled.

This smaller sensitivity, on the other hand, seems to be useful when the number of samples is not large enough. In the toy experiment with irrelevant hyperparameters,  `FanovaImportanceEvaluator` sometimes failed and ranked irrelevant hyperparameters higher than the relevant ones, while `MutualInformationImportanceEvaluator` were more likely to rank hyperparameters correctly.

### Standard error of estimated mutual information
In order to deal with the above-mentioned tendency of small sensitivity, I implemented a standard error estimator of mutual information estimate using the bootstrap method. I believe the estimates of the standard error is useful, as they give a good guideline on whether we can get rid of the parameter. (We can test a hypothesis H0: MI=0.)

Note that estimation of the standard error is not possible for FANOVA, because `FanovaImportanceEvaluator` takes much more time to calculate its importance than `MutualInformationImportanceEvaluator`. 

#### Scripts
You can find the code for this benchmark at my [Gist](https://gist.github.com/kstoneriv3/61c4155b4edda96b140e0025e4b7b70d).
#### Results
![image](https://user-images.githubusercontent.com/30857855/93806949-3bd7cf80-fc4a-11ea-933f-18af7d923eec.png)
↑Toy experiment where x0-x2 are equally relevant and x3-x5 are totally irrelevant. This is an example case where FANOVA fails.

![image](https://user-images.githubusercontent.com/30857855/93870161-1344e980-fccd-11ea-997c-2d4ac49704c4.png)

![image](https://user-images.githubusercontent.com/30857855/93870209-235cc900-fccd-11ea-83a7-1d177e6f8300.png)

![image](https://user-images.githubusercontent.com/30857855/93870737-f230c880-fccd-11ea-96a6-36d059e6db7b.png)

## TODOs
- [x] take some benchmarks to compare `MutualInformationImportanceEvaluator` with existing evaluators.  
- [ ] discuss whether or not to support mutual information importance evaluator in Optuna
- [ ] change / improve the design of the draft code

**Comment by kstoneriv3** [comment]
I updated the description after some modifications and banchmarking on my local code. Now, most of the issues that I initially encountered were solved and `MutualInformationImportanceEvaluator` looks promising.
