### ISSUE TITLE
Integrate multi-objective optimization module

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#1980]
## Motivation
In the current Optuna's codebase, the `optuna.multi_objective` module is separated from other modules. However, to improve maintenance and ensure code consistency, Optuna's basic modules (e.g. study, trial, etc) should be designed with multi-objective optimization in mind. 

PR #1961 was submitted, but this work will be split into several small PRs. This issue tracks the integration of the multi-objective optimization module.

## TODOs
- [x] Multi-dimensional study directions and trial values: fix RDB schema #2030.
- [x] Multi-dimensional study directions and trial values: fix `study`, `frozen trial`, and `storages` #1994.
- [x] Pruning system: fix `trial.report` and `trial.should_prune` #2135.
- [x] Multi-objective samplers: migrate `NSGAIISampler` #2150.
- [x] Multi-objective samplers: migrate `MOTPESampler` #2167.
- [x] Visualization module: migrate `plot_pareto_front` #2110, #2122.
- [x] Visualization module: fix single-objective plot functions #2112, #2117, #2118, #2120, #2121, #2137.
- [x] Misc: fix multi-objective examples #2123.
- [x] Misc: fix other modules which assume the single-objective optimization #2136.
- [x] Misc: deprecate the previous multi-objective module #2124.

**Comment by hvy** [comment]
Pinned this issue since I find myself coming back to it quite often and there was one slot left for the pins.

**Comment by hvy** [comment]
@not522 is working on `Study.trials_dataframe` to support MO studies. I think we can close this issue as resolved after that.

**Comment by hvy** [comment]
Let me close this issue as resolved now that https://github.com/optuna/optuna/pull/2181 addressing the above has been merged.
