### ISSUE TITLE
Release Tasks for v2.4.0

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#2033]
Optuna [v2.4.0](https://github.com/optuna/optuna/milestone/30) -- in early ~~December, 2020~~ January, 2021

Features (TBD):
- [x] Refactoring multi-objective optimization module #1994 #2030
- [x] Multi-objective optimization follow-ups (e.g. user friendly errors) #1980
- [x] Universal data transformer #1987
- [x] AllenNLP Executor options #1959, #2018
- [x] Partial Fixed Sampler #1892
- [x] BoTorch Sampler #1989 

Documentation
- [x] New tutorial #1722

Examples
- [x] MXNet Gluon example #1985

**Comment by hvy** [comment]
#1722 is now merged. However, the Read the Docs build is failing due to a timeout and must be fixed before the release.

**Comment by hvy** [comment]
PR addressing the above Read the Docs failure https://github.com/optuna/optuna/pull/2076.

**Comment by hvy** [comment]
Let me add https://github.com/optuna/optuna/pull/2082 to the milestone as well.

**Comment by hvy** [comment]
Let me close this one since v2.4 was released yesterday and it seems to be working fine. 

Here is the corresponding issue for the next v2.5 release, https://github.com/optuna/optuna/issues/2198.
