### ISSUE TITLE
Adding code & figure examples of `visualization.matplotlib` functions

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#2091]
Providing example code and figure for every function in `visualization.matplotlib` is useful for users to know the difference between the figure output by the corresponding function in the plotly backend, and for developers to detect visual bugs that cannot be detected by unit tests. Currently, some functions in `visualization.matplotlib` do not have example code and figure, so it would be better to provide them.

## How to add a code example and figure
- Write a code example with the matplotlib plot directive.
- See the docstring of the [edf function](https://github.com/optuna/optuna/blob/master/optuna/visualization/matplotlib/_edf.py) for an example

## Current status
- [x] `optuna.visualization.matplotlib.plot_contour` #2100 
- [x] `optuna.visualization.matplotlib.plot_edf`
- [x] `optuna.visualization.matplotlib.plot_intermediate_values`
- [x] `optuna.visualization.matplotlib.plot_optimization_history`
- [x] `optuna.visualization.matplotlib.plot_parallel_coordinate` #2097 
- [x] `optuna.visualization.matplotlib.plot_param_importances` #2098 
- [ ] `optuna.visualization.matplotlib.plot_slice` #2099

**Comment by keisuke-umezawa** [comment]
@nzw0301 Congrats for the last one mile!
