### ISSUE TITLE
Ask and Tell API Request

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#2177]
## Motivation

Please refer to the description in https://github.com/optuna/optuna/pull/2158. 

## Description

This is an issue to keep track of related PRs to Optuna's ask and tell API.

- [x] `Study.ask`, `Study.tell` #2158
- [x] ~`Study.report`, #2176~ Edit: Closed. See #2176.
- [x] ~`Study.should_prune` #2178~  Edit: Closed. See #2176.
- [x] ~Consider allowing `FrozenTrial`~ Edit: Closed. See #2176.
- [ ] Allow reporting and pruning by restoring Trials. #2213
- [x] Tutorial how to use Ask and tell
- [ ] Allow logging similar to `Study.optimize`

## Example

```python
# NOTE: Where `Trial`s are passed as arguments, trial numbers can be passed as well.

# Example 1: Simple case without pruning and no error handling.
trial = study.ask()
values = objective(trial)
study.tell(trial, values)

# Example 2: With error handling.
trial = study.ask()

values = None
try:
    values = objective(trial)
except TrialPruned:
    state = TrialState.PRUNED
except Exception:
    state = TrialState.FAIL
else:
    state = TrialState.COMPLETE
finally:
    study.tell(trial, values=values, state=state)

# Example 3: No `func` objective function.
trial = study.ask()

loss = None
state = TrialState.COMPLETE

lr = trial.suggest_float("lr", 1e-5, 1e-3, log=True)
n_layers = trial.suggest_int("n_layers", 3, 5)
# Evaluation follows. This can be scheduled arbitrarily by the user to other workers.
for epoch in range(epochs):
    loss = ...
    study.report(trial, loss, step=epoch)  # `Trial.report` also possible.
    if study.should_prune(trial):
        state = TrialState.PRUNED
        break

loss = ...  # Validation.

study.tell(trial, values=loss, state=state)
```

**Comment by Shawn513** [comment]
HI, I would like to ask: 
If i've already have some observation points and would like to use these data to tell the study. 
So first I will need to 
Trail = study.ask() 
then how can I set the trail's parameters to the already known data points  ? Here I noticed that there's trial.suggest_int("n_layers", 3, 5),  but this will be generated a new data point , is there any func could directly feed the data point like in Skopt?

**Comment by hvy** [comment]
You could probably use [`Study.enqueue_trial`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.enqueue_trial) for that. Something along the following.

```python
import optuna

study = optuna.create_study()
study.enqueue_trial({"n_layers": 3})
study.enqueue_trial({"n_layers": 4})

for i in range(3):
    trial = study.ask()
    x = trial.suggest_int("n_layers", 3, 5)

    if i == 0:
        assert x == 3
    elif i == 1:
        assert x == 4
    elif i == 2:
        assert 3 <= x <= 5  # Not queued, so suggested from the algorithm/sampler. 

    # You can still suggest other parameters.
    y = trial.suggest_float("lr", 1e-6, 1e-3, log=True) 

    study.tell(trial, value=...)
```

**Comment by Shawn513** [comment]
Thank you very much ！ I will use enqueue_trial to try.

**Comment by hvy** [comment]
Related PR to allow suggestions via `Study.ask` by passing distributions https://github.com/optuna/optuna/pull/2271

**Comment by hvy** [comment]
Added two items to the list in the description, namely one to add a tutorial and a second to allow logging.

**Comment by hvy** [comment]
Made it `no-stale` since the tutorial is ongoing. Thanks @not522 for the heads up.

**Comment by Crissman** [comment]
@hvy Seems mostly done. Shall we close this?

**Comment by hvy** [comment]
Thanks for checking. Yes, let me close it.
We can always come back to it later.
