### ISSUE TITLE
Release Tasks for v2.5.0

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#2198]
Tracking issue for Optuna [v2.5.0](https://github.com/optuna/optuna/milestone/31)

Features (TBD):

- [x] Ask and tell #2177 (partially)
- [x] (Experimental) Constrained NSGA-II #2175
- [x] RDB storage heartbeat #2190

**Comment by hvy** [comment]
Let me close this one since v2.5 was just released.

Here is the corresponding issue for the next v2.6 release, #2295.
