### ISSUE TITLE
TPE design discussion

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#2415]
## Descriptions
The Optuna's default sampling algorithm, TPE, has some options and drawbacks. This issue is a note to be addressed in the future. Please feel free to leave comments.

## TODOs
- [ ] Merge standard TPE and multivariate TPE
- [ ] Merge standard TPE and multi-objective TPE
    - API refinement of weight arguments
- [ ] Performance improvement on discrete optimization
    - Use some kernel (e.g. Aitchison-Aitken kernel) instead of a histogram-based approach
    - Impose a penalty on the already selected choices
- [ ] Constraint optimization support

**Comment by HideakiImamura** [comment]
Let me close this issue since the new tracking issue #2614 is created.
