### ISSUE TITLE
A major refactoring of Tree-structured Parzen Estimator

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#2614]
## Motivations

In Optuna, there are several variants of Tree-structured Parzen Estimator (TPE) such as univariate TPE, multivariate TPE, and multi-objective TPE. However, those implementations are overlapped. We've noticed that it is difficult to maintain them separately. Now, we have a plan to unify their implementations. This is a tracking issue of the major refactoring of TPE.

## Roadmap

- [x] Make multi-objective TPE in the `multi_objective` module a thin wrapper for that in the `samplers` module.  #2615
- [x] Separate the implementation of multi-objective TPE from other variants.  #2616
- [x] Unify the implementations of univariate and multivariate TPE.  #2618
- [x] Unify the implementations of single-objective and multi-objective TPE. `optuna/samplers/_tpe/multi_objective_sampler.py` will be removed. https://github.com/optuna/optuna/pull/2688 
- [x] List the test cases to be considered and add the missing cases.
- [x] Improve the speed.

**Comment by hvy** [comment]
Please note that I'm freezing the code for v2.9.0 now although this issue is marked (milestone) with this release and is still open. 

The last item of improving the speed was by the way addressed in https://github.com/optuna/optuna/pull/2816. Tests are probably remaining.

**Comment by contramundum53** [comment]
This issue has already been solved.
