### ISSUE TITLE
Follow-up of MLflowCallback

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2788]
## Motivation
Thanks to the great improvement by https://github.com/optuna/optuna/pull/2670, optuna provides a smoother connection to MLFLow via `MLflowCallback`. But we still have a TODO list to improve the codebase and its feature mentioned in the review of https://github.com/optuna/optuna/pull/2670.

## TODO tasks discussed in https://github.com/optuna/optuna/issues/2788#issuecomment-898890114 to close this issue

- [x] General code/docstring fixes mentioned in #2670 TODO list (https://github.com/optuna/optuna/pull/2855)
- [x] Introduction of multi-objective support  (https://github.com/optuna/optuna/pull/2863)
- [ ] Refactoring interface to be more similar to WeightsAndBiasesCallback (+ decoupling study name from mlflow experiment) (https://github.com/optuna/optuna/pull/2912)

Please see also the following `Description` for more detailed contexts.

---

## Description

Please see the discussion in the review. But we can separately work on this issue as follows:

- support multi-objective https://github.com/optuna/optuna/pull/2670#discussion_r633204507
- improve the docstring.
- improve the tag truncation https://github.com/optuna/optuna/pull/2670#discussion_r650478298

**Comment by nzw0301** [comment]
Hi @rafarui thank you for your feedback! Indeed, when we introduce `WeightsAndBiasesCallback` recently, it has [`wandb_kwargs`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.integration.WeightsAndBiasesCallback.html#optuna.integration.WeightsAndBiasesCallback) that are used for the initialisation of wandb. So we can add a similar argument to `MLflowCallback` for a more flexible interface as you mentioned.

**Comment by xadrianzetx** [comment]
Hi, I will work on that in following order (separate PRs):

* General code/docstring fixes mentioned in [#2670 TODO list](https://github.com/optuna/optuna/pull/2670#pullrequestreview-682465454)
* Introduction of multi-objective support
* Refactoring interface to be more similar to `WeightsAndBiasesCallback` (+ decoupling study name from mlflow experiment)

This order should keep things clear, let me know if you agree @nzw0301.

**Comment by nzw0301** [comment]
Thank you for sharing the plan! It sounds perfect.
