### ISSUE TITLE
Reintroduce the feature of n_jobs (multi-thread)

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#2937]
## Motivation
The feature of n_jobs (multi-thread) was deprecated in this [PR](https://github.com/optuna/optuna/pull/2560) because it is impractical in most use cases and can be reproduced by writing a few lines of code if users want to reproduce the same thing. However, some people on Twitter and 3 people on the [PR](https://github.com/optuna/optuna/pull/2560) wanted to reintroduce the feature. Based on the above, it is necessary to consider whether to reintroduce n_jobs (multi-thread) or not.

## Description

We would like to make a consensus whether to reintroduce n_jobs (multi-thread) or not. If reintroducing it, we will restore the n_jobs (multi-thread) argument. If not, we will consider appropriate alternatives and develop a plan for them. Also, we will decide that Optuna's data structures may continue to support multi-threading.

##  Consensus for the solution  (Added on Dec 17, 2011)
From the following reasons, we decided that we will continue to support the feature of `n_jobs`.

* We observed that more people wish to reintroduce this feature than people who claimed for misusing the feature.
* Also, this feature can be useful for tasks not blocked by GIL.

## TODOs
- [x] Make a consensus for the solution in this issue
- If reintroducing it,
    - [x] Remove deprecate decorator
    - [x] Provide enough information to avoid misuse of the feature e.g.
        -  [x] API reference
        -  [x] FAQ
        -  [x] etc
- ~If not,~
    - ~[ ] Create a plan to provide alternative solutions and documentation~
    - ~[ ] Make a consensus for Optuna's data structures~

## Reference
- https://github.com/optuna/optuna/issues/2950

**Comment by tsuga** [comment]
I'm wondering if process-based (by multiprocessing module) would be an option as well.

**Comment by keisuke-umezawa** [comment]
@tsuga Thank you for the comment. We will investigate multiprocess treatment in this issue https://github.com/optuna/optuna/issues/2950.

**Comment by keisuke-umezawa** [comment]
Update the description.

**Comment by HideakiImamura** [comment]
@keisuke-umezawa What other documentation needs to be enhanced besides the API reference and FAQ? (The `etc` part in the issue description.)

**Comment by keisuke-umezawa** [comment]
> @keisuke-umezawa What other documentation needs to be enhanced besides the API reference and FAQ? (The etc part in the issue description.)

Maybe, nothitng.

**Comment by HideakiImamura** [comment]
Let me close this issue since all tasks have done. Please feel free to reopen if you have any problems.
