### ISSUE TITLE
Determine the scope of application of CachedStorage

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#2938]
## Motivation
Currently, `CachedStorage` provides inconsistent functionality due to the following situations:

* `CachedStorage` only supports `RDBStorage`, because it is necessary to implement several methods to be supported by `CachedStorage`, and they are only implemented in `RDBStorage`. However, it is possible to input other storages when constructing `CachedStorage`, and it will cause an error.
* When we pass an instance of `RDBStorage` to `Study`, it is forcibly wrapped in CachedStorage, and it is always CachedStorage internally.

## Description

The solution will be decided in consideration of the following points. Also, the changes have been merged.

* As `CachedStorage` is not compatible with other storages than `RDBStorage`, we will decide it will support other storages and how to support other storages.
* The specifications for `get_storage` to convert `RDBStorage` to `CachedStorage` are well defined.
* Based on the above decision, the implementation of `CachedStorage` has been decided.
    * If the scope of application is only RDB Storage, introduce a mechanism to limit the usage only for `RDBStorage`.
    * If the scope of application includes other storages, consider the implementation method (if the implementation method is the same as the current one, include the arrangement of APIs that the storage must satisfy)

## TODOs
- [x] https://github.com/optuna/optuna/issues/3112
- [x] Make a consensus for the solution in this issue that `CachedStorage` will support other storages and how to support other storages. #3204
- [x] The specifications for `get_storage` to convert `RDBStorage` to `CachedStorage` are well defined. [conclusion](https://github.com/optuna/optuna/issues/2938#issuecomment-1035986042)
- [x] Implementation

### Necessary methods to implement for `CachedStorage` 
- [_get_trials](https://github.com/optuna/optuna/blob/master/optuna/storages/_rdb/storage.py#L870)
- [_create_new_trial](https://github.com/optuna/optuna/blob/master/optuna/storages/_rdb/storage.py#L506)
- [_check_and_set_param_distribution](https://github.com/optuna/optuna/blob/master/optuna/storages/_rdb/storage.py#L709)

**Comment by keisuke-umezawa** [comment]
## Note for `Make a consensus for the solution in this issue that CachedStorage will support other storages and how to support other storages.`

In my opinion, if we just implement `_get_trials` in a storage, we can provide the cache functionality for the storage. As it is not so difficult, we can make it mandatory to implement in each storage class.

Current status:
- RDBStorage: Implemented
- RedisStorage: Will be implemented in #3204 
- InMemoryStorage, BaseStorage, CachedStorage: No need for implementation

## Note for `The specifications for get_storage to convert RDBStorage to CachedStorage are well defined.`

### Current issue
- [ ] RDBStorage is automatically converted to CachedStorage. Therefore, users may feel difficulty to understand the structure.
- [ ] As it is always converted to CachedStorage, users can not use raw RDBStorage, although we do not know there are such users actually.
