### ISSUE TITLE
Stabilize _callbacks.py

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#2993]
## Motivation

There are currently two callback functions provided by Optuna, `MaxTrialsCallback` and `RetryFailedTrialsCallback`. In this development item, we will consider removing experimental labels from them.

In particular, there are the following concerns regarding `RetryFailedTrialsCallback`:
(1) The heartbeat function of `RDBStorage` and `_Cached Storage`, which is the premise of this function, is not sufficiently dog ​​fooded.
(2) When this function and `GridSampler` are used at the same time, the failed parameter is retried and the grid is consumed at the same time. That is, the failed parameter is preferentially sampled and its grid is no longer evaluated. This problem is similar to the problem with `enqueue_trial` described in "Stabilize study.py".
(3) The information of intermediate values ​​is not inherited in the trial that is retried by this function.

We will consider removing experimental labels after resolving these concerns.

[Update 2022/01/14]: We have decided there is no concern about `MaxTrialsCallback`, so we can remove the experimental label right now. On the other hand, the heartbeat functionality itself has not yet been fully exploited, so there are concerns about `RetryFailedTrialsCallback`. We need more document and improvement. See the below more details.

## What should we do

For `MaxTrialsCallback`
- [x] Remove the experimental label from `MaxTrialsCallback`. #3261

For `RetryFailedTrialsCallback`
- [x] Add FAQ entry for heatbeat. https://github.com/optuna/optuna/pull/3229 
- [x] ~Add a tutorial page for heartbeat.~ We have decided not to add a tutorial for heaetbeat since it is difficult to reproduce the situation where a trial is stale. We lead to the FAQ page and the example page instead of it. #3294
- [x] Fix the behavior of `RetryFailedTrialsCallback` so that it retry the latest failed trial. https://github.com/optuna/optuna/pull/3223
- [x] The behavior when `RetryFailedTrialsCallback` and `GridSampler` are used at the same time has been discussed and corrected appropriately.　https://github.com/optuna/optuna/pull/2946
- [x] Add an option to determine whether retry trials inherit intermediate values or not. #3269
- [x] ~After finishing all of above tasks, discuss whether the experimental label is removed or not at the end of April 2022.~ We discussed storages and concluded in #2943 that there should be a major refactoring of `BaseStorage`. Since the heartbeat functionality is also likely to undergo major changes, including interface changes, it was decided not to remove the `RetryFailedTrialsCallback`'s experimental in V3.

**Comment by HideakiImamura** [comment]
As pointed above, we discussed storages and concluded in https://github.com/optuna/optuna/issues/2943 that there should be a major refactoring of BaseStorage. Since the heartbeat functionality is also likely to undergo major changes, including interface changes, it was decided not to remove the RetryFailedTrialsCallback's experimental in V3.

Let me close this issue.
