### ISSUE TITLE
Introduce a rich benchmark environment in CI

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#3245]
This is the prerequisite task for #2964, #2906 and #2951.

## Motivations

Recently, a benchmarking environment using [`kurobako`](https://github.com/optuna/kurobako) was introduced in Optuna for benchmarking the performance evaluation of sampling and pruning algorithms. The benchmarking feature itself is still experimental and we need to add more problems/features.

Please feel free to leave any comments/feedback for the benchmarking feature.

## What should we do

- [x] Support the multi-objective problem. In `kurobako`, there is some multi-objective problem such that ZDD and NAS-bench (C). We can just use those problems. In addition, visualization of benchmark results is different from single-objective problems. We can show the pareto-front plot and optimization-history plot for each objective coordinate. (We should discuss this point.) #3271
    - [ ] https://github.com/optuna/optuna/pull/3691 
- [x] Support problems other than `kurobako`. We plan to support [Bayesmark](https://github.com/uber/bayesmark). #3354. See https://github.com/optuna/optuna/issues/3464 for the remaining tasks.
- [x] Make NAS-Bench-201 and 301 available in benchmark. See https://arxiv.org/abs/2201.13396 and https://arxiv.org/abs/2008.09777.
    - [x] https://github.com/optuna/optuna/pull/3465
    - ~[ ] NAS-Bench-301~
- [x] Make WFG problems available in benchmark. See https://github.com/HideakiImamura/WFGtestSuite. #3349

## References
See https://github.com/optuna/optuna/tree/master/benchmarks for more details about the current benchmark environment.

**Comment by HideakiImamura** [comment]
Note that @xadrianzetx is working on the second item in https://github.com/xadrianzetx/dev-optuna-bayesmark.

**Comment by HideakiImamura** [comment]
Now, NAS-Bench-201 and 301 are proposed, but they are not available in kurobako. It would be great to make it available in kurobako. 
- https://arxiv.org/abs/2201.13396
- https://arxiv.org/abs/2008.09777

**Comment by HideakiImamura** [comment]
Note that @kei-mo is working on the fourth item.

**Comment by hvy** [comment]
For the record, let me add an additional reference https://github.com/optuna/optuna/pull/3155.

**Comment by HideakiImamura** [comment]
Note that @contramundum53 will work on the third item.

**Comment by divyanshugit** [comment]
@HideakiImamura  If anything is left in this issue then I would love to work on it.

**Comment by HideakiImamura** [comment]
We have decided not to take a benchmark for multi-objective optimization in Optuna V3. Let me close this issue. I will create another issue to setup the benchmark environment for multi-objective optimization.
