### ISSUE TITLE
Use test stubs of samplers where we can in unit tests using samplers

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#3724]
### Motivation

To make unit tests using samplers deterministic , we would like to use test stubs instead of instances which have non-deterministic behaviors. In this issue, we would like to use test stubs for samplers (e.g. DeterministicRelativeSampler, FirstTrialOnlyRandomSampler) where we can so that we make unit tests using samplers deterministic.

Furthermore, to make unit tests using samplers deterministic, there are 5 ways used in Optuna. e.g.

- Use a fixed random seed to make RandomSampler deterministic
- Use a mock to fix suggested values
- Use a test stub to fix suggested values
- Use a single value to fix suggested values
- Test suggested values are in the expected range. e.g. 1 <= x <=2

We will align a way to write unit tests using samplers if needed.

#### Current direction
1. If we do not need to check suggested values in a unit test,
    1. we should `use a fixed random seed to make RandomSampler deterministic`.
1. If we need to check suggested values in a unit test,
    1. we should choose one of ways from the following:
        - Use a mock to fix suggested values
        - Use a test stub to fix suggested values
        - Use a single value to fix suggested values
        - Test suggested values are in the expected range. e.g. 1 <= x <=2
    1. And, the current direction is that `using a test stub to fix suggested values`.

However, we have not concluded that `using a test stub to fix suggested values` is always the best way when we need to check suggested values in a unit test, especially when `using a single value to fix suggested values` and `testing suggested values are in the expected range`. We will discuss it in this issue.

Note: `If the current test stubs of samplers are not enough to reproduce the current functions of the unit tests, we may introduce new test stubs for samplers.`

#### Todos
- [ ] Implement new test stubs if needed
    - [x] DeterministicSampler #3827 
- [ ] Make a consensus that which solution is appropriate when we need to check suggested values in a unit test
- [ ] Use test stubs for samplers in the following files:
    - [x] Unit tests `using a mock to fix suggested values` #3807
        - [x] https://github.com/optuna/optuna/blob/master/tests/trial_tests/test_trial.py
            - test_suggest_uniform
            - test_suggest_loguniform
            - test_suggest_discrete_uniform
            - test_suggest_int
            - test_suggest_int_log
    - [ ] Unit tests `using a single value to fix suggested values`
        - [ ] https://github.com/optuna/optuna/blob/master/tests/study_tests/test_study.py
            - test_callbacks
        - [ ] https://github.com/optuna/optuna/blob/master/tests/study_tests/test_dataframe.py
            - test_trials_dataframe
            - test_trials_dataframe_with_failure
            - test_trials_dataframe_with_multi_objective_optimization
        - [ ] https://github.com/optuna/optuna/blob/master/tests/integration_tests/lightgbm_tuner_tests/test_optimize.py
            - test_create_stepwise_study
    - [ ] Unit tests `testing suggested values are in the expected range`
        - [ ] https://github.com/optuna/optuna/blob/master/tests/study_tests/test_study.py
        - [ ] https://github.com/optuna/optuna/blob/master/tests/integration_tests/test_pytorch_distributed.py
        - [ ] https://github.com/optuna/optuna/blob/master/tests/integration_tests/test_chainermn.py
        - [ ] https://github.com/optuna/optuna/blob/master/tests/storages_tests/rdb_tests/test_storage.py
        - [ ] https://github.com/optuna/optuna/blob/master/tests/test_cli.py

**Comment by c-bata** [comment]
I checked the rest of test cases (`test_study.py`, `test_dataframe.py`, and `integration_tests/lightgbm_tuner_tests/test_optimize.py`). I think that using `DeterministicSampler` in these tests does not simplify these tests.

So we can close this issue after #3807 is merged.

**Comment by keisuke-umezawa** [comment]
@c-bata 
I clarified the situation more in the issue description.

> I checked the rest of test cases (test_study.py, test_dataframe.py, and integration_tests/lightgbm_tuner_tests/test_optimize.py). I think that using DeterministicSampler in these tests does not simplify these tests.

We may still need some discussion that which way should be used for `using a single value to fix suggested values`. We can discuss it in this issue.

**Comment by hvy** [comment]
Note that https://github.com/optuna/optuna/pull/3807 has been merged now.
