### ISSUE TITLE
Standardize citation format and linking rules for papers in the document

### ISSUE THREAD

**Issue by Alnusjaponica** [optuna/optuna#4682]
### Motivation
It would be better to  establish a set of guidelines to ensure consistent citation format and linking for the papers referenced within our document. This will improve readability, provide proper credit to the original authors, and facilitate easy access to the cited works. The purpose of this issue is to discuss and define the rules that will be followed throughout the document.

### Suggestion
- Citation Format for Reference List and In-text Citations:
  - There are several citation format traditionally used in each field, such as [AMS Style](https://www.ams.org/publications/authors/AMS-StyleGuide-online.pdf), [CSE Style](https://dal.ca.libguides.com/CitationStyleGuide/CSE), [IEEE Style](https://ieeeauthorcenter.ieee.org/wp-content/uploads/IEEE-Reference-Guide.pdf), and so on. Any of them will be fine as long as it is consistent.
- Docstrings Style:
  - https://pypi.org/project/sphinxcontrib-bibtex/
  - Use reference section as in https://www.sphinx-doc.org/ja/master/usage/extensions/napoleon.html
- Linking to Papers:
  - Use [DOI](https://www.doi.org/)s.

### Tasks
- [ ] Discuss and finalize the rules for citation and linking format.
- [ ] List up all references to papers in the document
- [ ] Update the document with the standardized citation format and links for all referenced papers.

Feel free to add any suggestions, concerns, or examples related to citation format and linking that should be considered during the discussion.

**Comment by Alnusjaponica** [comment]
Following links are a list of (implicit or explicit) citations in the documentation.
- Optuna
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/README.md?plain=1#L165-L166
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/docs/source/index.rst?plain=1#L105-L107
- benchmarks
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/benchmarks/bayesmark/report_bayesmark.py#L151
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/benchmarks/bayesmark/report_bayesmark.py#L246
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/benchmarks/bayesmark/report_template.md?plain=1#L11
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/_hypervolume/hssp.py#L21-L22
- Fanova
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/importance/_fanova/_evaluator.py#L25-L27
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/importance/_fanova/_fanova.py#L3-L4
 - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/multi_objective/samplers/_motpe.py#L35
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/multi_objective/samplers/_motpe.py#L33-L34
- Hyperband
    - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_hyperband.py#L25
    - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_hyperband.py#L62
    - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_hyperband.py#L191
    - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_hyperband.py#L223
    - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_hyperband.py#L239
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_hyperband.py#L196
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_successive_halving.py#L15
- Successive Halving
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_successive_halving.py#L18
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_successive_halving.py#L73
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_successive_halving.py#L99
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/pruners/_successive_halving.py#L105

- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_nsgaiii.py#L49-L51
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_nsgaiii.py#L52-L55
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_nsgaiii.py#L424
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_qmc.py#L37-L39
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_tpe/multi_objective_sampler.py#L29-L30
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_tpe/multi_objective_sampler.py#L31
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_cmaes.py#L90-L91
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_cmaes.py#L92-L95
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_cmaes.py#L96-L99
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_cmaes.py#L100-L102
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_cmaes.py#L103-L105
- TPE
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_tpe/sampler.py#L71-L72
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_tpe/sampler.py#L131
- TPE
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_tpe/sampler.py#L73-L74
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_tpe/sampler.py#L124-L125
- Multiobjective TPE
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_tpe/sampler.py#L75-L76
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_tpe/sampler.py#L134
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_tpe/sampler.py#L77
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/_tpe/sampler.py#L141
- NSGAII
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/multi_objective/samplers/_nsga2.py#L37-L38
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_sampler.py#L48-L49
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_blxalpha.py#L16-L18
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_blxalpha.py#L37-L38
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_sbx.py#L17-L20
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_sbx.py#L41-L42
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_sbx.py#L17-L20
- SPXCrossover
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_spx.py#L18-L22
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_spx.py#L41
- UNDXCrossover
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_undx.py#L17-L22
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_undx.py#L72
- UniformCrossover
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_uniform.py#L13-L16
  - https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_uniform.py#L35-L36
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_vsbx.py#L18-L21
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/samplers/nsgaii/_crossovers/_vsbx.py#L42-L43
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/terminator/terminator.py#L31
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/visualization/_edf.py#L52
- https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/tutorial/10_key_features/003_efficient_optimization_algorithms.py#L154

**Comment by Alnusjaponica** [comment]
It seems [sphinxcontrib-bibtex · PyPI](https://pypi.org/project/sphinxcontrib-bibtex/) would be good solution.
