### ISSUE TITLE
Follow up `artifacts` implementation

### ISSUE THREAD

**Issue by Alnusjaponica** [optuna/optuna#4843]
### What is an issue?
This is a tracking issue to followup #4823, #4763 and #4840.

### Motivation
There are some remaining tasks to brush up  `artifacts` implementation. 

First of all, there are no example code in the docstrings of `FileSystemArtifactStore` and `Boto3ArtifactStore`. This is because we need to implement `upload_artifact` to use them. Also, `Boto3ArtifactStore` is not tested in `test_upload_artifact.py`.

In addition, initializer of `FileSystemArtifactStore` does not have proper check for the given path. It would be convenient for the initializer to checks if given path is valid and try to create proper directory.

## Task Description
Add Example code to `FileSystemArtifactStore` and `Boto3ArtifactStore` after #4823 is merged and reflect them to the document.

- [x] Add example code to `FileSystemArtifactStore`.
- [x] Add example code to `Boto3ArtifactStore`.
- [x] Add `docs/source/reference/artifact.rst` to properly setup document.
- [ ] Add test for `Boto3ArtifactStore` in `test_upload_artifact.py`.
- [ ] Treat given path properly in the initializer of `FileSystemArtifactStore`.

Please refer to original `optuna-dashboard` code to write examples.

https://github.com/optuna/optuna-dashboard/blob/08ff9fa13f36a171eefc9858b173cbf2ab2a3e2a/optuna_dashboard/artifact/boto3.py#L22-L35

https://github.com/optuna/optuna-dashboard/blob/08ff9fa13f36a171eefc9858b173cbf2ab2a3e2a/optuna_dashboard/artifact/file_system.py#L17-L30

**Comment by gen740** [comment]
After merging #4823. It's will be better to add `Boto3ArtifactStore` backend to `test_upload_artifact.py` for follow-up.

**Comment by Alnusjaponica** [comment]
Thanks! I updated the task description.
