### ISSUE TITLE
Drop Python 2 support.

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#713]
Python 2 will be dropped as it goes EOL (as announced in the last couple of release notes).

### TODOs

- [x] Remove Python 2 Circle CI jobs. https://github.com/optuna/optuna/pull/710
- [x] Remove `six`. https://github.com/optuna/optuna/pull/714
- [x] Remove `__future__`. https://github.com/optuna/optuna/pull/715
- [ ] Rewrite type hints using Python 3.5 compatible modern ones.
- [ ] Update docs.
- [ ] Update coding style guidelines.

### Trivial TODOs 

- [x] Remove `__ne__` definition where `__eq__` is defined. https://stackoverflow.com/questions/390250/elegant-ways-to-support-equivalence-equality-in-python-classes

**Comment by hvy** [comment]
Closing in favor of #711, which is a sufficient subset of this issue.
